 #for Windows
#[target.x86_64-pc-windows-msvc]
#linker = "rust-lld.exe"


 [build]
 rustflags = ["-Z", "threads=8"]

 #Cranelift --> Faster comptime; Slower runtime
#[unstable]
#codegen-backend = true

#[profile.dev]
#codegen-backend = "cranelift"

#[profile.dev.package."*"]
#codegen-backend = "llvm"